name: My first github actions

on: push

jobs:
  my_first_djob:
    runs-on: ubuntu-latest
    steps:
    - name: get repository
      uses: actions/checkout@v4

    - name: read file
      run: | 
        echo "Welcome to learn github actions "
        ls -l
        cat README.md

    - name: Generate ascii code
      run: cowsay -f dragron "Run to cover i'am a dragon .... RAWWR" >> draggon.txt
  