name: multi jobs 
on: push 
jobs:
    build-job:
        runs-on: ubuntu-latest
        steps:
            - name: installer cowsay
              run: sudo apt-get install cowsay -y
            
            - name: creation du fichier 
              run: cowsay -f dragon "Run to cover i'am a dragon .... RAWWR" >> dragon.txt

            - name: upload file to artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt

    test-job:
        needs: build-job # ce element est utiliser pour lancer les job de maniere sequentiel ( build-job sera executer avant test-job)
        runs-on: ubuntu-latest
        steps: 
            - name: attaente 
              run: sleep 3

            - name: download file to artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file

            - name: recherche du fichier 
              run: grep -i dragon "dragon.txt"

    deploy-job:
        needs: test-job
        concurrency: 
          group: stagging 
          cancel-in-progress: true 
        runs-on: ubuntu-latest
        steps: 
            - name: download file to artifact
              uses: actions/download-artifact@v4
              with:
                name: dragon-file

            - name: deployement object 
              run: cat dragon.txt

            - name: affichage
              run: echo " deploying ... ..."
            - name: add sleep time
              run: sleep 200

